
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-valheim-zingerweb-services-v1beta1-valheimserver
  failurePolicy: Fail
  name: mvalheimserver.kb.io
  rules:
  - apiGroups:
    - valheim.zingerweb.services
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - valheimservers
  sideEffects: None
