# permissions for end users to view valheimservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: valheimserver-viewer-role
rules:
- apiGroups:
  - valheim.zingerweb.services
  resources:
  - valheimservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - valheim.zingerweb.services
  resources:
  - valheimservers/status
  verbs:
  - get
