# permissions for end users to view valheimverticalscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: valheimverticalscaler-viewer-role
rules:
- apiGroups:
  - valheim.zingerweb.services
  resources:
  - valheimverticalscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - valheim.zingerweb.services
  resources:
  - valheimverticalscalers/status
  verbs:
  - get
