# permissions for end users to edit valheimverticalscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: valheimverticalscaler-editor-role
rules:
- apiGroups:
  - valheim.zingerweb.services
  resources:
  - valheimverticalscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - valheim.zingerweb.services
  resources:
  - valheimverticalscalers/status
  verbs:
  - get
