// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWS) DeepCopyInto(out *AWS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWS.
func (in *AWS) DeepCopy() *AWS {
	if in == nil {
		return nil
	}
	out := new(AWS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sDeployment) DeepCopyInto(out *K8sDeployment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sDeployment.
func (in *K8sDeployment) DeepCopy() *K8sDeployment {
	if in == nil {
		return nil
	}
	out := new(K8sDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValheimVerticalScaler) DeepCopyInto(out *ValheimVerticalScaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValheimVerticalScaler.
func (in *ValheimVerticalScaler) DeepCopy() *ValheimVerticalScaler {
	if in == nil {
		return nil
	}
	out := new(ValheimVerticalScaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ValheimVerticalScaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValheimVerticalScalerList) DeepCopyInto(out *ValheimVerticalScalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ValheimVerticalScaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValheimVerticalScalerList.
func (in *ValheimVerticalScalerList) DeepCopy() *ValheimVerticalScalerList {
	if in == nil {
		return nil
	}
	out := new(ValheimVerticalScalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ValheimVerticalScalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValheimVerticalScalerSpec) DeepCopyInto(out *ValheimVerticalScalerSpec) {
	*out = *in
	out.AWS = in.AWS
	out.K8sDeployment = in.K8sDeployment
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValheimVerticalScalerSpec.
func (in *ValheimVerticalScalerSpec) DeepCopy() *ValheimVerticalScalerSpec {
	if in == nil {
		return nil
	}
	out := new(ValheimVerticalScalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValheimVerticalScalerStatus) DeepCopyInto(out *ValheimVerticalScalerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValheimVerticalScalerStatus.
func (in *ValheimVerticalScalerStatus) DeepCopy() *ValheimVerticalScalerStatus {
	if in == nil {
		return nil
	}
	out := new(ValheimVerticalScalerStatus)
	in.DeepCopyInto(out)
	return out
}
